name: rsm-sdd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch>=1.12
  - torchvision>=0.13
  - numpy
  - pyyaml
  - tqdm
  - pillow
  - matplotlib
  - scikit-learn
  - pip:
      - pytest
