DATASET:
  NAME: cifar100
  ROOT: D:/LCX/PAMA-SDD/data
  BATCH_SIZE: 64
  NUM_WORKERS: 2

SOLVER:
  EPOCHS: 240
  LR: 0.05
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  NESTEROV: false
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WARMUP_EPOCHS: 30
  AMP: false
  CHANNELS_LAST: true
  DEVICE: ""
  SEED: 3407

STUDENT:
  NAME: resnet8x4
  NUM_CLASSES: 100
  DISTILL_LEVELS: [1, 2, 4]
  PAMA_OUT_CHANNELS: 256
  PAMA_HEADS: 4
  PAMA_AGENT_NUM: 49

TEACHER:
  NAME: resnet32x4
  NUM_CLASSES: 100
  DISTILL_LEVELS: [1, 2, 4]
  PAMA_OUT_CHANNELS: 256
  PAMA_HEADS: 4
  PAMA_AGENT_NUM: 49

DISTILLER:
  NAME: KD

KD:
  TEMPERATURE: 4.0
  LOSS:
    CE_WEIGHT: 1.0
    KD_WEIGHT: 1.0

DKD:
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 2.0
  T: 4.0

NKD:
  CE_WEIGHT: 1.0
  T: 1.0
  GAMMA: 1.5

SDD:
  M: "[1,2,4]"

PAMA:
  GAC_WEIGHT: 1.0

